POST http://127.0.0.1:8000/api/v1/modem/changeIp
Accept: application/json
Content-Type: application/json
Authorization: Bearer WXyIyYAMvj7OOzIj8aVELfvOgtrKd4i8VMQHK4B0uMoQ5IWPZvxK8y7PX5xG9teu

{
    "modem_id": 1
}
