POST http://127.0.0.1:8000/api/v1/user/confirmLostPassword
Accept: application/json
Content-Type: application/json

{
    "password": "testtest3",
    "password_confirmation": "testtest3",
    "password_recovery_token": "XQogSPPCtgDBFsNemLrFlywyYg6y91TmD7aLk9GVRlBc3vsXIgxSjFd9PAzF1Tkn",
    "email": "delrossofabio@gmail.com"
}
